---
- name: install ntp
  apt:
    name: ntp
    state: latest
  notify:
    - register-autostart-service-ntp

- name: install postgresql and related libraries
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql-{{ hortonworks_postgres_version }}
    - libpq-dev
    - python-psycopg2
    - libpostgresql-jdbc-java
  when: hortonworks_ambari_server == true
  notify:
    - register-autostart-service-postgresql

- name: install ambari-server
  apt:
    name: ambari-server
    state: latest
  when: hortonworks_ambari_server == true
  notify:
    - register-autostart-service-ambari-server
    - restart-service-ambari-server

- name: install ambari-agent
  apt:
    name: ambari-agent
    state: latest
  when: hortonworks_ambari_agent == true
  notify:
    - register-autostart-service-ambari-agent
    - restart-service-ambari-agent
