---
- name: install ntp
  apt:
    name: ntp
    state: latest
  notify:
    - register-autostart-service-ntp
    - start-service-ntp

- name: install postgresql and related libraries
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql-{{ hortonworks_postgres_version }}
    - libpq-dev
    - python-psycopg2
    - libpostgresql-jdbc-java
    #- mysql-server mysql-client libmysql-java (/usr/share/java/mysql.jar -> /var/lib/ambari-server/resources/mysql-connector-java.jar)
    # vi /etc/mysql/mysql.conf.d/mysqld.cnf
    # bind-address            = 0.0.0.0
    # GRANT ALL PRIVILEGES ON *.* TO 'hive'@'%';
    # /usr/hdp/current/hive-server2/bin/schematool -initSchema -dbType mysql -userName hive -passWord pass -verbose
  when: hortonworks_ambari_server == true
  notify:
    - register-autostart-service-postgresql
    - start-service-postgresql

- name: install ambari-server
  apt:
    name: ambari-server
    state: latest
  when: hortonworks_ambari_server == true
  notify:
    - register-autostart-service-ambari-server
    - start-service-ambari-server

- name: install ambari-agent
  apt:
    name: ambari-agent
    state: latest
  when: hortonworks_ambari_agent == true
  notify:
    - register-autostart-service-ambari-agent
    - start-service-ambari-agent
