---
presto_package_mirror: "https://repo1.maven.org/maven2/com/facebook/presto"
presto_version: "0.213"

presto_archive_filename: "presto-server-{{presto_version}}.tar.gz"
presto_archive_url: "{{ presto_package_mirror }}/presto-server/{{ presto_version }}/{{ presto_archive_filename }}"
presto_archive_hash_sha1: "fa389433287addaefe8eb926510ce74ef05814b9"

presto_client_filename: "presto-cli-{{ presto_version }}-executable.jar"
presto_client_url: "{{ presto_package_mirror }}/presto-cli/{{ presto_version }}/{{ presto_client_filename }}"
presto_client_hash_sha1: "2fb5806d8889724e8df69444242a059d997f38b2"

presto_unpack_dir: "/opt"
presto_install_dir: "/opt/presto-server-{{ presto_version }}"
presto_link_dir: "/opt/presto"
presto_data_dir: /var/presto/data

presto_os_user_name: "hdfs"
presto_os_group_name: "{{ presto_os_user_name }}"
presto_os_user_pass: "encrypted-password-see-ansible-user-module-docs"

presto_coordinator_host: "{{ groups['presto-coordinator'].0 }}"
presto_hive_metastore_host: "{{ groups['presto-coordinator'].0 }}"
presto_hive_allow_drop_table: true

presto_install_coordinator: false
presto_install_worker: false
presto_install_client: false

presto_query_max_memory: 2GB
presto_query_max_memory_per_node: 2GB
presto_query_max_total_memory_per_node: 2GB
presto_max_heap_size: 3G
presto_http_port: 8080

presto_cluster_name: data-platform
presto_node_id: "{{presto_cluster_name}}-{{ ansible_fqdn }}"
