---
hadoop_package_mirror: "http://www-eu.apache.org/dist"
hadoop_version: "3.0.3"

hadoop_archive_filename: "hadoop-{{ hadoop_version }}.tar.gz"
hadoop_archive_url: "{{ hadoop_package_mirror }}/hadoop/common/hadoop-{{ hadoop_version }}/{{ hadoop_archive_filename }}"
hadoop_archive_hash_sha256: "db96e2c0d0d5352d8984892dfac4e27c0e682d98a497b7e04ee97c3e2019277a"

hadoop_unpack_dir: "/opt"
hadoop_install_dir: "/opt/hadoop-{{ hadoop_version }}"
hadoop_config_dir: "{{ hadoop_install_dir }}/etc/hadoop"
hadoop_link_dir: "/opt/hadoop"
hadoop_data_dir: /var/hadoop/data
hadoop_dfs_namenode_name_dir: "{{ hadoop_data_dir }}/namenode"
hadoop_dfs_datanode_data_dir: "{{ hadoop_data_dir }}/datanode"

hadoop_os_user_name: "hdfs"
hadoop_os_group_name: "{{ hadoop_os_user_name }}"
hadoop_os_user_pass: "encrypted-password-see-ansible-user-module-docs"

hadoop_host_name: "{{ ansible_fqdn }}"
hadoop_master_host_name: "{{ ansible_fqdn }}"
hadoop_worker_host_names: "{{ ansible_fqdn }}"
hadoop_dfs_replication: 1

hadoop_install_master: false
hadoop_install_worker: false
hadoop_install_client: false
