---
# https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html
- name: add Confluent's public key
  apt_key:
    url: http://packages.confluent.io/deb/{{ confluent_platform_version }}/archive.key
    state: present

- name: add Confluent's .deb repository
  apt_repository:
    repo: "deb [arch=amd64] http://packages.confluent.io/deb/{{ confluent_platform_version }} stable main"
    state: present
    update_cache: true
