- name: copy a Kafdrop systemd service file
  template:
    src: kafdrop.service
    dest: /lib/systemd/system/kafdrop.service
    owner: root
    group: root
    mode: 0644
  notify:
    - register-autostart-service-kafdrop
