---
- name: install add-apt-repostory
  become: yes
  apt:
    name: software-properties-common
    state: latest

- name: add webupd8 Oracle Java repo
  become: yes
  apt_repository:
    repo: "ppa:webupd8team/java"

- name: accept Java 8 license
  become: yes
  debconf:
    name: "oracle-java8-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"

- name: install Oracle Java 8
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-unlimited-jce-policy
    - oracle-java8-set-default
