---
# Configuration
letsencrypt_domain_names: # If you use freemyip.com for domain names, put them here
  - "input.data-platform.example"
  - "schema-registry.data-platform.example"
letsencrypt_notifications_email: "username@gmail.com"
letsencrypt_truststore_file_name: "truststore.p12"
letsencrypt_truststore_passwd: "Password_123"
letsencrypt_renew_log_path: "/var/log/letsencrypt_renew.log"
